language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libv8-dev

matrix:
  include:
    - os: linux
       r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  slack:
    secure: R4f1zyyQAVzdetfOwEG+vcS3u5shmX1S4YQZCgD/NQcuUN9V4APsfzVoFuk92fb4UfjgcDjBcK38TIHXoDG8SaF2cMm12i1eZvj6/utmB/gXXa5cItHyTZPaq4ElScUGDGe4yL9fuleqkDPAG2Au57/phjweMXzMQg2ZUGYtSDI=
  email:
    on_success: change
    on_failure: change

